// Desi Taboo word bank — every target and taboo entry is a single word.
// Each entry: [word, difficulty (1 easy / 2 medium / 3 hard), category, [5 taboo words]]
const WORDS = [
// ---------- EASY ----------
["Chai", 1, "Food", ["Tea", "Cup", "Milk", "Sugar", "Morning"]],
["Samosa", 1, "Food", ["Snack", "Potato", "Fried", "Triangle", "Chutney"]],
["Cricket", 1, "Sports", ["Bat", "Ball", "Wicket", "IPL", "Sachin"]],
["Diwali", 1, "Festivals", ["Lights", "Diya", "Festival", "Crackers", "Lakshmi"]],
["Holi", 1, "Festivals", ["Colours", "Water", "Festival", "Gulal", "Pichkari"]],
["Rickshaw", 1, "Daily Life", ["Auto", "Three", "Wheeler", "Meter", "Driver"]],
["Taj", 1, "Places", ["Agra", "Shahjahan", "Marble", "Mahal", "Love"]],
["Bollywood", 1, "Movies", ["Movie", "Mumbai", "Actor", "Film", "Song"]],
["Sari", 1, "Culture", ["Dress", "Drape", "Blouse", "Women", "Silk"]],
["Biryani", 1, "Food", ["Rice", "Hyderabad", "Chicken", "Dum", "Raita"]],
["Mango", 1, "Food", ["Alphonso", "Fruit", "Summer", "King", "Yellow"]],
["Rupee", 1, "Daily Life", ["Money", "Currency", "Note", "Coin", "Paisa"]],
["Mumbai", 1, "Places", ["Bombay", "City", "Bollywood", "Sea", "Local"]],
["Sachin", 1, "Cricket", ["Tendulkar", "Master", "Blaster", "Century", "Batsman"]],
["Shahrukh", 1, "Movies", ["Khan", "King", "Actor", "Romance", "Mannat"]],
["Dosa", 1, "Food", ["Crispy", "Batter", "Sambar", "South", "Rice"]],
["Paneer", 1, "Food", ["Cheese", "Cottage", "Curry", "Butter", "Tikka"]],
["Elephant", 1, "Nature", ["Trunk", "Tusk", "Animal", "Big", "Ganesha"]],
["Peacock", 1, "Nature", ["Bird", "National", "Feather", "Dance", "Blue"]],
["Tiger", 1, "Nature", ["National", "Animal", "Stripes", "Jungle", "Roar"]],
["Lotus", 1, "Nature", ["Flower", "National", "Pond", "Pink", "Petals"]],
["Mehndi", 1, "Culture", ["Henna", "Hands", "Wedding", "Design", "Bride"]],
["Bindi", 1, "Culture", ["Forehead", "Dot", "Red", "Women", "Sticker"]],
["Rangoli", 1, "Culture", ["Colours", "Powder", "Floor", "Design", "Diwali"]],
["Kite", 1, "Daily Life", ["Fly", "String", "Sky", "Manjha", "Sankranti"]],
["Momos", 1, "Food", ["Dumpling", "Steam", "Chutney", "Tibet", "Nepal"]],
["Laddoo", 1, "Food", ["Sweet", "Round", "Besan", "Motichoor", "Ganesh"]],
["Golgappa", 1, "Food", ["Puchka", "Water", "Puri", "Spicy", "Street"]],
["Maggi", 1, "Food", ["Noodles", "Two", "Minutes", "Masala", "Instant"]],
["Vada", 1, "Food", ["Pav", "Mumbai", "Potato", "Fried", "Chutney"]],
["Ganesh", 1, "Mythology", ["Elephant", "God", "Modak", "Chaturthi", "Trunk"]],
["Hanuman", 1, "Mythology", ["Monkey", "God", "Ram", "Strong", "Bajrang"]],
["Yoga", 1, "Daily Life", ["Exercise", "Asana", "Stretch", "Baba", "Meditation"]],
["Bindaas", 1, "Hinglish", ["Cool", "Carefree", "Tension", "Attitude", "Mumbai"]],
["Jugaad", 1, "Hinglish", ["Hack", "Fix", "Trick", "Cheap", "Solution"]],
["Shaadi", 1, "Culture", ["Wedding", "Bride", "Groom", "Baraat", "Marriage"]],
["Monsoon", 1, "Nature", ["Rain", "Season", "Umbrella", "Flood", "July"]],
["Cow", 1, "Nature", ["Milk", "Holy", "Animal", "Gau", "Moo"]],
["Scooter", 1, "Daily Life", ["Activa", "Two", "Wheeler", "Ride", "Helmet"]],
["Goa", 1, "Places", ["Beach", "Party", "Feni", "Portuguese", "Sea"]],
["Delhi", 1, "Places", ["Capital", "Metro", "Fort", "Parliament", "Pollution"]],
["Roti", 1, "Food", ["Chapati", "Wheat", "Round", "Tawa", "Bread"]],
["Lassi", 1, "Food", ["Curd", "Drink", "Punjab", "Sweet", "Yogurt"]],
["Jalebi", 1, "Food", ["Sweet", "Orange", "Spiral", "Syrup", "Crispy"]],
["Kurta", 1, "Culture", ["Shirt", "Long", "Cotton", "Pyjama", "Ethnic"]],
["Dhoni", 1, "Cricket", ["Captain", "Cool", "Helicopter", "Wicketkeeper", "Ranchi"]],
["Kohli", 1, "Cricket", ["Virat", "Captain", "Chase", "Anushka", "RCB"]],
["IPL", 1, "Cricket", ["Cricket", "League", "T20", "Auction", "Franchise"]],
["Nariyal", 1, "Food", ["Coconut", "Water", "Beach", "Drink", "Tree"]],
["Traffic", 1, "Daily Life", ["Jam", "Horn", "Signal", "Cars", "Road"]],
["Train", 1, "Daily Life", ["Railway", "Local", "Ticket", "Station", "Platform"]],
["Metro", 1, "Daily Life", ["Train", "Underground", "Delhi", "Token", "Station"]],
["Bhangra", 1, "Culture", ["Dance", "Punjab", "Dhol", "Balle", "Wedding"]],
["Dhol", 1, "Music", ["Drum", "Beat", "Bhangra", "Wedding", "Music"]],
["Kabaddi", 1, "Sports", ["Sport", "Raid", "Breath", "Tag", "Pro"]],
["Ludo", 1, "Games", ["Board", "Dice", "Game", "Token", "Four"]],
["Carrom", 1, "Games", ["Board", "Striker", "Coin", "Queen", "Powder"]],
["Gully", 1, "Sports", ["Street", "Lane", "Cricket", "Narrow", "Boy"]],
["Paratha", 1, "Food", ["Stuffed", "Potato", "Butter", "Punjab", "Breakfast"]],
["Tapri", 1, "Food", ["Tea", "Stall", "Chai", "Cutting", "Roadside"]],
["Chowmein", 1, "Food", ["Noodles", "Chinese", "Street", "Fried", "Wok"]],
["Rajma", 1, "Food", ["Beans", "Rice", "Sunday", "Punjab", "Curry"]],
["Ola", 1, "Brands", ["Cab", "App", "Ride", "Book", "Uber"]],
["Selfie", 1, "Daily Life", ["Photo", "Phone", "Camera", "Pose", "Front"]],
["WhatsApp", 1, "Tech", ["Chat", "Message", "Green", "Forward", "Group"]],
["Aadhaar", 1, "Daily Life", ["Card", "Number", "ID", "Twelve", "UIDAI"]],
["Paytm", 1, "Brands", ["Wallet", "Recharge", "UPI", "Karo", "App"]],
["Namaste", 1, "Hinglish", ["Hello", "Greeting", "Hands", "Fold", "Bow"]],
["Kulfi", 1, "Food", ["Frozen", "Stick", "Malai", "Pista", "Cold"]],
["Bhelpuri", 1, "Food", ["Puffed", "Rice", "Chaat", "Beach", "Mumbai"]],
["Bheem", 1, "TV", ["Chhota", "Cartoon", "Laddoo", "Dholakpur", "Strong"]],
["Amul", 1, "Brands", ["Butter", "Girl", "Milk", "Utterly", "Gujarat"]],
["Parle", 1, "Brands", ["Biscuit", "Girl", "Tea", "Glucose", "Cheap"]],
["Tandoori", 1, "Food", ["Chicken", "Red", "Oven", "Clay", "Roast"]],
["Idli", 1, "Food", ["Steamed", "Rice", "South", "Round", "Sambar"]],
["Thali", 1, "Food", ["Plate", "Meal", "Unlimited", "Variety", "Katori"]],
["Achaar", 1, "Food", ["Pickle", "Mango", "Oil", "Spicy", "Jar"]],
["Papad", 1, "Food", ["Crispy", "Roast", "Lijjat", "Thin", "Fry"]],
["Kurkure", 1, "Brands", ["Snack", "Crunchy", "Masala", "Munch", "Chips"]],
["Zomato", 1, "Brands", ["Food", "Delivery", "App", "Order", "Swiggy"]],
// ---------- MEDIUM ----------
["Amritsar", 2, "Places", ["Golden", "Temple", "Sikh", "Punjab", "Langar"]],
["Kumbh", 2, "Festivals", ["Mela", "Ganga", "Sadhu", "Prayagraj", "Crowd"]],
["Rakhi", 2, "Festivals", ["Thread", "Sister", "Brother", "Wrist", "Raksha"]],
["Sindoor", 2, "Culture", ["Red", "Vermilion", "Married", "Forehead", "Hair"]],
["Onam", 2, "Festivals", ["Kerala", "Sadya", "Boat", "Pookalam", "Mahabali"]],
["Pongal", 2, "Festivals", ["Tamil", "Harvest", "Rice", "Sugarcane", "Sun"]],
["Durga", 2, "Festivals", ["Puja", "Bengal", "Pandal", "Goddess", "Lion"]],
["Navratri", 2, "Festivals", ["Garba", "Nine", "Dandiya", "Gujarat", "Nights"]],
["Eid", 2, "Festivals", ["Sewai", "Moon", "Ramzan", "Biryani", "Namaz"]],
["Baraat", 2, "Culture", ["Groom", "Horse", "Band", "Dance", "Wedding"]],
["Sangeet", 2, "Culture", ["Wedding", "Dance", "Song", "Night", "Family"]],
["Bidaai", 2, "Culture", ["Bride", "Cry", "Leave", "Wedding", "Farewell"]],
["Dabbawala", 2, "Daily Life", ["Mumbai", "Lunch", "Tiffin", "Deliver", "Bicycle"]],
["Local", 2, "Daily Life", ["Train", "Mumbai", "Crowd", "Compartment", "Rush"]],
["Chandni", 2, "Places", ["Chowk", "Delhi", "Market", "Old", "Moonlight"]],
["Chowpatty", 2, "Places", ["Beach", "Mumbai", "Bhelpuri", "Sand", "Ganpati"]],
["Gateway", 2, "Places", ["India", "Mumbai", "Monument", "Arch", "Sea"]],
["Akbar", 2, "History", ["Mughal", "Emperor", "Birbal", "Jodha", "Agra"]],
["Sansad", 2, "Daily Life", ["Parliament", "Delhi", "MP", "Bill", "Speaker"]],
["Qutub", 2, "Places", ["Minar", "Delhi", "Tower", "Tall", "Minaret"]],
["Amer", 2, "Places", ["Fort", "Jaipur", "Elephant", "Palace", "Hill"]],
["Charminar", 2, "Places", ["Hyderabad", "Four", "Minarets", "Nizam", "Bangles"]],
["Howrah", 2, "Places", ["Bridge", "Kolkata", "Hooghly", "Station", "Steel"]],
["Konark", 2, "Places", ["Odisha", "Sun", "Temple", "Wheel", "Chariot"]],
["Alleppey", 2, "Places", ["Backwaters", "Houseboat", "Kerala", "Coconut", "Lake"]],
["Ladakh", 2, "Places", ["Mountain", "Bike", "Pangong", "Buddhist", "Cold"]],
["Kashmir", 2, "Places", ["Valley", "Shikara", "Dal", "Paradise", "Snow"]],
["Rishikesh", 2, "Places", ["Ganga", "Rafting", "Yoga", "Beatles", "Jhula"]],
["Varanasi", 2, "Places", ["Ghat", "Ganga", "Aarti", "Banaras", "Temple"]],
["Jaipur", 2, "Places", ["Pink", "City", "Rajasthan", "Palace", "Fort"]],
["Udaipur", 2, "Places", ["Lake", "Palace", "Rajasthan", "City", "White"]],
["Bengaluru", 2, "Places", ["IT", "Traffic", "Garden", "Silicon", "Bangalore"]],
["Hyderabad", 2, "Places", ["Biryani", "Charminar", "Nizam", "Pearls", "Cyberabad"]],
["Kolkata", 2, "Places", ["Bengal", "Tram", "Howrah", "Rosogolla", "Calcutta"]],
["Chennai", 2, "Places", ["Madras", "Marina", "Tamil", "Kaapi", "Beach"]],
["Ahmedabad", 2, "Places", ["Gujarat", "Sabarmati", "Dhokla", "Gandhi", "Kite"]],
["Bajaj", 2, "Brands", ["Scooter", "Hamara", "Chetak", "Pulsar", "Auto"]],
["Tata", 2, "Brands", ["Ratan", "Salt", "Steel", "Nano", "Group"]],
["Reliance", 2, "Brands", ["Jio", "Ambani", "Mukesh", "Sim", "Antilia"]],
["Flipkart", 2, "Brands", ["Shopping", "Online", "Billion", "Amazon", "Sale"]],
["Bullet", 2, "Brands", ["Enfield", "Bike", "Thump", "Classic", "Royal"]],
["Maruti", 2, "Brands", ["Car", "Suzuki", "Alto", "Swift", "800"]],
["Kingfisher", 2, "Brands", ["Beer", "Mallya", "Airline", "Bird", "Calendar"]],
["Frooti", 2, "Brands", ["Mango", "Drink", "Tetra", "Fresh", "Juice"]],
["Fevicol", 2, "Brands", ["Glue", "Stick", "Ad", "Bond", "Jod"]],
["Lifebuoy", 2, "Brands", ["Soap", "Health", "Red", "Jingle", "Bath"]],
["Chyawanprash", 2, "Brands", ["Immunity", "Amla", "Jam", "Winter", "Dabur"]],
["Rasgulla", 2, "Food", ["Bengal", "Sweet", "Spongy", "Syrup", "White"]],
["Mysore", 2, "Food", ["Pak", "Sweet", "Karnataka", "Palace", "Sandalwood"]],
["Bhature", 2, "Food", ["Chole", "Fried", "Puri", "Delhi", "Chickpea"]],
["Dhokla", 2, "Food", ["Gujarat", "Steamed", "Besan", "Yellow", "Spongy"]],
["Bhaji", 2, "Food", ["Pav", "Mumbai", "Butter", "Mash", "Vegetable"]],
["Kaapi", 2, "Food", ["Coffee", "Filter", "South", "Tumbler", "Decoction"]],
["Litti", 2, "Food", ["Chokha", "Bihar", "Sattu", "Baingan", "Roasted"]],
["Wazwan", 2, "Food", ["Kashmir", "Feast", "Mutton", "Rogan", "Wedding"]],
["Saag", 2, "Food", ["Sarson", "Mustard", "Makki", "Roti", "Punjab"]],
["Ilish", 2, "Food", ["Fish", "Bengal", "Bones", "Mustard", "Hilsa"]],
["Katli", 2, "Food", ["Kaju", "Cashew", "Sweet", "Diamond", "Silver"]],
["Bhindi", 2, "Food", ["Okra", "Ladyfinger", "Vegetable", "Green", "Sabzi"]],
["Rancho", 2, "Movies", ["Idiots", "Aamir", "College", "Chatur", "Engineering"]],
["Sholay", 2, "Movies", ["Gabbar", "Jai", "Veeru", "Basanti", "Kitne"]],
["DDLJ", 2, "Movies", ["Raj", "Simran", "Train", "Switzerland", "Palat"]],
["Dangal", 2, "Movies", ["Wrestling", "Aamir", "Geeta", "Babita", "Haryana"]],
["Baahubali", 2, "Movies", ["Katappa", "Prabhas", "Mahishmati", "Why", "Rajamouli"]],
["RRR", 2, "Movies", ["Naatu", "Charan", "NTR", "Oscar", "Rajamouli"]],
["Lagaan", 2, "Movies", ["Cricket", "Aamir", "British", "Tax", "Bhuvan"]],
["Amitabh", 2, "Movies", ["Bachchan", "Angry", "KBC", "Actor", "Jaya"]],
["Rajinikanth", 2, "Movies", ["Thalaiva", "Superstar", "Tamil", "Style", "Robot"]],
["Salman", 2, "Movies", ["Khan", "Bhai", "Bigg", "Dabangg", "Shirtless"]],
["Aamir", 2, "Movies", ["Khan", "Perfectionist", "Idiots", "Dangal", "Actor"]],
["Deepika", 2, "Movies", ["Padukone", "Ranveer", "Actress", "Padmaavat", "Dimples"]],
["Priyanka", 2, "Movies", ["Chopra", "Nick", "Jonas", "Hollywood", "Actress"]],
["Rahman", 2, "Music", ["Music", "Oscar", "Composer", "Roja", "Slumdog"]],
["Lata", 2, "Music", ["Mangeshkar", "Singer", "Nightingale", "Voice", "Legend"]],
["Kishore", 2, "Music", ["Kumar", "Singer", "Yodel", "Voice", "Songs"]],
["KBC", 2, "TV", ["Quiz", "Amitabh", "Crorepati", "Lock", "Lifeline"]],
["Roadies", 2, "TV", ["MTV", "Reality", "Raghu", "Bike", "Task"]],
["Jethalal", 2, "TV", ["Taarak", "Gokuldham", "Comedy", "Serial", "Babita"]],
["CID", 2, "TV", ["Daya", "Darwaza", "ACP", "Pradyuman", "Crime"]],
["Ramayan", 2, "Mythology", ["Valmiki", "Sita", "Ravan", "Lanka", "Epic"]],
["Mahabharat", 2, "Mythology", ["Kurukshetra", "Pandav", "Kaurav", "Krishna", "Epic"]],
["Krishna", 2, "Mythology", ["Flute", "Blue", "Butter", "Radha", "Gokul"]],
["Shiva", 2, "Mythology", ["Trishul", "Eye", "Kailash", "Nandi", "Destroyer"]],
["Ravan", 2, "Mythology", ["Ten", "Heads", "Lanka", "Dussehra", "Villain"]],
["Arjun", 2, "Mythology", ["Archer", "Pandav", "Krishna", "Bow", "Draupadi"]],
["Karna", 2, "Mythology", ["Kavach", "Kundal", "Sun", "Generous", "Mahabharat"]],
["Gandhi", 2, "History", ["Bapu", "Charkha", "Ahimsa", "Salt", "Father"]],
["Nehru", 2, "History", ["First", "Minister", "Jacket", "Rose", "Chacha"]],
["Bhagat", 2, "History", ["Singh", "Freedom", "Hanged", "Inquilab", "Lahore"]],
["Kalam", 2, "History", ["Abdul", "Missile", "President", "Scientist", "Rameswaram"]],
["Tagore", 2, "History", ["Rabindranath", "Nobel", "Poet", "Bengal", "Gitanjali"]],
["Chandrayaan", 2, "Tech", ["Moon", "ISRO", "Rocket", "Lander", "Vikram"]],
["ISRO", 2, "Tech", ["Space", "Rocket", "Satellite", "Bengaluru", "Mars"]],
["UPI", 2, "Tech", ["Payment", "QR", "Scan", "PhonePe", "GPay"]],
["Hockey", 2, "Sports", ["Stick", "National", "Dhyan", "Olympic", "Goal"]],
["Neeraj", 2, "Sports", ["Chopra", "Javelin", "Gold", "Olympic", "Throw"]],
["Sindhu", 2, "Sports", ["Badminton", "Shuttle", "Olympic", "Medal", "Hyderabad"]],
["Kom", 2, "Sports", ["Mary", "Boxing", "Manipur", "Punch", "Olympic"]],
["Kapil", 2, "Cricket", ["Dev", "1983", "Haryana", "Hurricane", "Allrounder"]],
["Rohit", 2, "Cricket", ["Sharma", "Hitman", "Mumbai", "Captain", "Opener"]],
["Tiffin", 2, "Daily Life", ["Lunch", "Box", "Steel", "Office", "Dabba"]],
["Chappal", 2, "Daily Life", ["Slipper", "Footwear", "Kolhapuri", "Rubber", "Sandal"]],
["Nazar", 2, "Hinglish", ["Evil", "Lemon", "Chilli", "Tika", "Battu"]],
["Bandh", 2, "Hinglish", ["Strike", "Shutdown", "Protest", "Close", "Hartal"]],
["Izzat", 2, "Hinglish", ["Honour", "Respect", "Family", "Pride", "Society"]],
["Arranged", 2, "Culture", ["Marriage", "Parents", "Rishta", "Match", "Biodata"]],
["Bargaining", 2, "Daily Life", ["Price", "Haggle", "Discount", "Market", "Bhaiya"]],
["Dupatta", 2, "Culture", ["Scarf", "Salwar", "Drape", "Cloth", "Kameez"]],
["Lungi", 2, "Culture", ["Cloth", "Wrap", "South", "Waist", "Dhoti"]],
["Tiranga", 2, "Culture", ["Flag", "Saffron", "White", "Green", "Tricolour"]],
["Antakshari", 2, "Games", ["Song", "Game", "Letter", "Last", "Sing"]],
["Langdi", 2, "Games", ["Hop", "Leg", "Chase", "Game", "Tag"]],
["Haldi", 2, "Food", ["Turmeric", "Yellow", "Wedding", "Spice", "Doodh"]],
["Ghee", 2, "Food", ["Butter", "Clarified", "Cow", "Desi", "Cooking"]],
["Gur", 2, "Food", ["Jaggery", "Sugar", "Brown", "Sugarcane", "Sweet"]],
["Tulsi", 2, "Nature", ["Basil", "Plant", "Holy", "Courtyard", "Leaves"]],
["Neem", 2, "Nature", ["Tree", "Bitter", "Datun", "Leaves", "Medicine"]],
["Darjeeling", 2, "Places", ["Tea", "Hills", "Train", "Kanchenjunga", "Bengal"]],
["Andaman", 2, "Places", ["Islands", "Jail", "Beach", "Scuba", "Nicobar"]],
["Kanyakumari", 2, "Places", ["Tip", "South", "Sunrise", "Oceans", "Vivekananda"]],
["Tirupati", 2, "Places", ["Balaji", "Laddoo", "Temple", "Andhra", "Hair"]],
["Vaishno", 2, "Places", ["Devi", "Katra", "Trek", "Jammu", "Cave"]],
["Kedarnath", 2, "Places", ["Shiva", "Uttarakhand", "Trek", "Flood", "Himalaya"]],
["Demonetisation", 2, "History", ["Notes", "500", "1000", "Ban", "2016"]],
["Sensex", 2, "Daily Life", ["Stock", "Market", "Bombay", "Index", "Dalal"]],
// ---------- HARD ----------
["Sanskrit", 3, "Culture", ["Language", "Ancient", "Vedas", "Shloka", "Devanagari"]],
["Chakra", 3, "Culture", ["Ashoka", "Flag", "Wheel", "Blue", "Spokes"]],
["Panchayat", 3, "Daily Life", ["Village", "Sarpanch", "Council", "Local", "Gram"]],
["Charcha", 3, "Hinglish", ["Chai", "Modi", "Talk", "Discussion", "Election"]],
["Aunty", 3, "Hinglish", ["Neighbour", "Gossip", "Beta", "Society", "Uncle"]],
["Kal", 3, "Hinglish", ["Tomorrow", "Yesterday", "Day", "Time", "Aaj"]],
["Rishta", 3, "Hinglish", ["Proposal", "Marriage", "Aunty", "Match", "Arranged"]],
["Sasta", 3, "Hinglish", ["Cheap", "Price", "Mehenga", "Discount", "Deal"]],
["Jhoola", 3, "Daily Life", ["Swing", "Rope", "Tree", "Park", "Push"]],
["Baniyan", 3, "Daily Life", ["Vest", "Undershirt", "Cotton", "White", "Sleeveless"]],
["Ghunghat", 3, "Culture", ["Veil", "Bride", "Face", "Cover", "Pallu"]],
["Anarkali", 3, "Culture", ["Suit", "Dress", "Flared", "Mughal", "Salim"]],
["Kohinoor", 3, "History", ["Diamond", "Queen", "Britain", "Crown", "Stolen"]],
["Vande", 3, "History", ["Mataram", "Song", "National", "Bankim", "Motherland"]],
["Anthem", 3, "Culture", ["Jana", "Gana", "Tagore", "National", "Stand"]],
["Sutta", 3, "Hinglish", ["Cigarette", "Chai", "Tapri", "Smoke", "Break"]],
["Nukkad", 3, "Hinglish", ["Corner", "Street", "Natak", "Gully", "Chai"]],
["Adda", 3, "Hinglish", ["Hangout", "Gossip", "Bengali", "Friends", "Chat"]],
["Sarkar", 3, "Hinglish", ["Government", "Modi", "Power", "State", "Ruling"]],
["Babu", 3, "Hinglish", ["Clerk", "Government", "Office", "File", "Bureaucrat"]],
["Chaiwala", 3, "Daily Life", ["Tea", "Seller", "Modi", "Tapri", "Kettle"]],
["Ambassador", 3, "History", ["Car", "Hindustan", "White", "Government", "Old"]],
["Doordarshan", 3, "TV", ["Channel", "Government", "Old", "Logo", "DD"]],
["Shaktimaan", 3, "TV", ["Superhero", "Khanna", "Spin", "Gangadhar", "Serial"]],
["Malgudi", 3, "TV", ["Days", "Serial", "Narayan", "Swami", "Doordarshan"]],
["Rasna", 3, "Brands", ["Drink", "Powder", "Love", "Orange", "Summer"]],
["Nirma", 3, "Brands", ["Detergent", "Washing", "Powder", "Girl", "Jingle"]],
["Bournvita", 3, "Brands", ["Chocolate", "Milk", "Powder", "Cadbury", "Kids"]],
["Boroline", 3, "Brands", ["Cream", "Green", "Tube", "Antiseptic", "Bengal"]],
["Monk", 3, "Brands", ["Old", "Rum", "Dark", "Bottle", "Winter"]],
["Gilli", 3, "Games", ["Danda", "Stick", "Game", "Village", "Hit"]],
["Lagori", 3, "Games", ["Stones", "Ball", "Game", "Seven", "Pithu"]],
["Kanche", 3, "Games", ["Marbles", "Glass", "Game", "Flick", "Kids"]],
["Chhath", 3, "Festivals", ["Puja", "Bihar", "Sun", "River", "Soop"]],
["Bihu", 3, "Festivals", ["Assam", "Dance", "Harvest", "Festival", "Bohag"]],
["Hornbill", 3, "Festivals", ["Festival", "Nagaland", "Tribe", "Bird", "Kohima"]],
["Pushkar", 3, "Festivals", ["Mela", "Camel", "Rajasthan", "Fair", "Lake"]],
["Jallikattu", 3, "Festivals", ["Bull", "Tamil", "Pongal", "Tame", "Ban"]],
["Kathakali", 3, "Culture", ["Kerala", "Dance", "Face", "Green", "Makeup"]],
["Bharatanatyam", 3, "Culture", ["Dance", "Classical", "Tamil", "Mudra", "Ghungroo"]],
["Sitar", 3, "Music", ["Instrument", "Strings", "Ravi", "Classical", "Music"]],
["Tabla", 3, "Music", ["Drum", "Zakir", "Beat", "Pair", "Classical"]],
["Ghungroo", 3, "Music", ["Anklet", "Bells", "Dance", "Sound", "Feet"]],
["Madhubani", 3, "Culture", ["Painting", "Bihar", "Art", "Folk", "Mithila"]],
["Warli", 3, "Culture", ["Painting", "Tribal", "Maharashtra", "Figures", "White"]],
["Pashmina", 3, "Culture", ["Shawl", "Kashmir", "Wool", "Soft", "Expensive"]],
["Banarasi", 3, "Culture", ["Sari", "Silk", "Varanasi", "Wedding", "Zari"]],
["Kanjeevaram", 3, "Culture", ["Sari", "Silk", "Tamil", "Wedding", "Gold"]],
["Ayurveda", 3, "Culture", ["Medicine", "Herbs", "Ancient", "Vaidya", "Dosha"]],
["Sattu", 3, "Food", ["Bihar", "Flour", "Gram", "Drink", "Litti"]],
["Kokum", 3, "Food", ["Konkan", "Fruit", "Sherbet", "Sour", "Purple"]],
["Chikki", 3, "Food", ["Peanut", "Jaggery", "Lonavala", "Brittle", "Sweet"]],
["Jolokia", 3, "Food", ["Bhut", "Chilli", "Assam", "Ghost", "Spicy"]],
["Santra", 3, "Food", ["Orange", "Nagpur", "Fruit", "Citrus", "Juice"]],
["Sundarbans", 3, "Places", ["Mangrove", "Tiger", "Bengal", "Delta", "Forest"]],
["Kutch", 3, "Places", ["Rann", "White", "Desert", "Salt", "Gujarat"]],
["Hampi", 3, "Places", ["Ruins", "Karnataka", "Vijayanagara", "Boulders", "UNESCO"]],
["Khajuraho", 3, "Places", ["Temple", "Sculptures", "Carvings", "Chandela", "Erotic"]],
["Ajanta", 3, "Places", ["Ellora", "Caves", "Maharashtra", "Buddhist", "Paintings"]],
["Madurai", 3, "Places", ["Meenakshi", "Temple", "Gopuram", "Tamil", "Jigarthanda"]],
["Amarnath", 3, "Places", ["Cave", "Ice", "Lingam", "Yatra", "Kashmir"]],
["Bodhi", 3, "Places", ["Tree", "Buddha", "Gaya", "Enlightenment", "Bihar"]],
["Sabarmati", 3, "History", ["Ashram", "Gandhi", "Ahmedabad", "River", "Charkha"]],
["Jallianwala", 3, "History", ["Bagh", "Amritsar", "Massacre", "Dyer", "Bullet"]],
["Dandi", 3, "History", ["March", "Salt", "Gandhi", "Walk", "Tax"]],
["Chipko", 3, "History", ["Movement", "Trees", "Hug", "Uttarakhand", "Forest"]],
["Swaminathan", 3, "History", ["Green", "Revolution", "Wheat", "Farming", "Scientist"]],
["Kurien", 3, "History", ["Milk", "Amul", "Flood", "Dairy", "Anand"]],
["GST", 3, "Daily Life", ["Tax", "Goods", "Services", "Nation", "Bill"]],
["Speaker", 3, "Daily Life", ["Lok", "Sabha", "Parliament", "Chair", "House"]],
["MLA", 3, "Daily Life", ["Assembly", "Vidhan", "Legislator", "State", "Election"]],
["Judiciary", 3, "Daily Life", ["Court", "Judge", "Supreme", "Verdict", "Law"]],
["RBI", 3, "Daily Life", ["Bank", "Governor", "Reserve", "Repo", "Currency"]],
["Mangalyaan", 3, "Tech", ["Mars", "ISRO", "Orbit", "Cheap", "Mission"]],
["Wizard", 3, "Sports", ["Hockey", "Dhyan", "Chand", "Magic", "Olympic"]],
["Milkha", 3, "Sports", ["Singh", "Flying", "Sikh", "Runner", "Bhaag"]],
["Chhetri", 3, "Sports", ["Sunil", "Football", "Captain", "Goal", "Striker"]],
["Anand", 3, "Sports", ["Viswanathan", "Chess", "Grandmaster", "Champion", "Chennai"]],
["Kumble", 3, "Cricket", ["Anil", "Spinner", "Jumbo", "Ten", "Bengaluru"]],
["Dravid", 3, "Cricket", ["Rahul", "Wall", "Coach", "Defence", "Dependable"]],
["Bumrah", 3, "Cricket", ["Jasprit", "Yorker", "Fast", "Bowler", "Action"]],
["Dhoom", 3, "Movies", ["Bike", "Abhishek", "Uday", "Thief", "Machale"]],
["Dharavi", 3, "Movies", ["Slum", "Mumbai", "Gully", "Rap", "Boy"]],
["Andhadhun", 3, "Movies", ["Blind", "Piano", "Ayushmann", "Tabu", "Rabbit"]],
["Drishyam", 3, "Movies", ["Ajay", "Mohanlal", "Police", "Alibi", "October"]],
["ZNMD", 3, "Movies", ["Spain", "Roadtrip", "Hrithik", "Tomatina", "Friends"]],
["Kantara", 3, "Movies", ["Kannada", "Kola", "Shetty", "Forest", "Deity"]],
["Anupam", 3, "Movies", ["Kher", "Actor", "Bald", "Veteran", "DDLJ"]],
["Patekar", 3, "Movies", ["Nana", "Actor", "Loud", "Welcome", "Marathi"]],
["Marie", 3, "Food", ["Biscuit", "Tea", "Dip", "Parle", "Evening"]],
["Bhutta", 3, "Food", ["Corn", "Roasted", "Lemon", "Monsoon", "Cob"]],
["Kanji", 3, "Food", ["Carrot", "Fermented", "Drink", "Black", "Holi"]],
];
