// Desi Taboo word bank.
// Each entry: [word, difficulty (1 easy / 2 medium / 3 hard), category, [5 taboo words]]
const WORDS = [
// ---------- EASY ----------
["Chai",1,"Food",["Tea","Cup","Milk","Sugar","Morning"]],
["Samosa",1,"Food",["Snack","Potato","Fried","Triangle","Chutney"]],
["Cricket",1,"Sports",["Bat","Ball","Wicket","IPL","Sachin"]],
["Diwali",1,"Festivals",["Lights","Diya","Festival","Crackers","Lakshmi"]],
["Holi",1,"Festivals",["Colours","Water","Festival","Gulal","Pichkari"]],
["Auto Rickshaw",1,"Daily Life",["Three","Wheeler","Meter","Driver","Yellow"]],
["Taj Mahal",1,"Places",["Agra","Shah Jahan","Marble","Monument","Love"]],
["Bollywood",1,"Movies",["Movie","Mumbai","Actor","Film","Song"]],
["Sari",1,"Culture",["Dress","Drape","Blouse","Women","Silk"]],
["Biryani",1,"Food",["Rice","Hyderabad","Chicken","Dum","Raita"]],
["Mango",1,"Food",["Alphonso","Fruit","Summer","King","Yellow"]],
["Rupee",1,"Daily Life",["Money","Currency","Note","Coin","Paisa"]],
["Mumbai",1,"Places",["Bombay","City","Bollywood","Sea","Local"]],
["Sachin Tendulkar",1,"Cricket",["Master","Blaster","Century","Batsman","God"]],
["Shah Rukh Khan",1,"Movies",["King","Actor","Bollywood","Romance","Mannat"]],
["Dosa",1,"Food",["Crispy","Batter","Sambar","South","Rice"]],
["Paneer",1,"Food",["Cheese","Cottage","Curry","Butter","Tikka"]],
["Elephant",1,"Nature",["Trunk","Tusk","Animal","Big","Ganesha"]],
["Peacock",1,"Nature",["Bird","National","Feather","Dance","Blue"]],
["Tiger",1,"Nature",["National","Animal","Stripes","Jungle","Roar"]],
["Lotus",1,"Nature",["Flower","National","Pond","Pink","Petals"]],
["Mehndi",1,"Culture",["Henna","Hands","Wedding","Design","Bride"]],
["Bindi",1,"Culture",["Forehead","Dot","Red","Women","Sticker"]],
["Rangoli",1,"Culture",["Colours","Powder","Floor","Design","Diwali"]],
["Kite",1,"Daily Life",["Fly","String","Sky","Manjha","Sankranti"]],
["Momos",1,"Food",["Dumpling","Steam","Chutney","Tibet","Nepal"]],
["Gulab Jamun",1,"Food",["Sweet","Syrup","Round","Brown","Dessert"]],
["Pani Puri",1,"Food",["Golgappa","Water","Puchka","Street","Spicy"]],
["Maggi",1,"Food",["Noodles","Two","Minutes","Masala","Instant"]],
["Vada Pav",1,"Food",["Mumbai","Burger","Bread","Potato","Chutney"]],
["Ganesh",1,"Mythology",["Elephant","God","Modak","Chaturthi","Trunk"]],
["Hanuman",1,"Mythology",["Monkey","God","Ram","Strong","Bajrang"]],
["Yoga",1,"Daily Life",["Exercise","Asana","Stretch","Baba","Meditation"]],
["Bindaas",1,"Hinglish",["Cool","Carefree","Tension","Attitude","Mumbai"]],
["Jugaad",1,"Hinglish",["Hack","Fix","Trick","Cheap","Solution"]],
["Shaadi",1,"Culture",["Wedding","Bride","Groom","Baraat","Marriage"]],
["Monsoon",1,"Nature",["Rain","Season","Umbrella","Flood","July"]],
["Cow",1,"Nature",["Milk","Holy","Animal","Gau","Moo"]],
["Scooter",1,"Daily Life",["Activa","Two","Wheeler","Ride","Helmet"]],
["Goa",1,"Places",["Beach","Party","Feni","Portuguese","Sea"]],
["Delhi",1,"Places",["Capital","Metro","Red Fort","Chandni Chowk","Pollution"]],
["Roti",1,"Food",["Chapati","Wheat","Round","Tawa","Bread"]],
["Lassi",1,"Food",["Curd","Drink","Punjab","Sweet","Yogurt"]],
["Jalebi",1,"Food",["Sweet","Orange","Spiral","Syrup","Crispy"]],
["Kurta",1,"Culture",["Shirt","Long","Cotton","Pyjama","Ethnic"]],
["MS Dhoni",1,"Cricket",["Captain","Cool","Helicopter","Wicketkeeper","Ranchi"]],
["Virat Kohli",1,"Cricket",["Captain","Run","Chase","Anushka","RCB"]],
["IPL",1,"Cricket",["Cricket","League","T20","Auction","Franchise"]],
["Nariyal Pani",1,"Food",["Coconut","Water","Beach","Drink","Straw"]],
["Traffic",1,"Daily Life",["Jam","Horn","Signal","Cars","Road"]],
["Train",1,"Daily Life",["Railway","Local","Ticket","Station","Platform"]],
["Metro",1,"Daily Life",["Train","Underground","Delhi","Token","Station"]],
["Bhangra",1,"Culture",["Dance","Punjab","Dhol","Balle","Wedding"]],
["Dhol",1,"Music",["Drum","Beat","Bhangra","Wedding","Music"]],
["Kabaddi",1,"Sports",["Sport","Raid","Breath","Tag","Pro"]],
["Ludo",1,"Games",["Board","Dice","Game","Token","Four"]],
["Carrom",1,"Games",["Board","Striker","Coin","Queen","Powder"]],
["Gully Cricket",1,"Sports",["Street","Bat","Ball","Tennis","Kids"]],
["Aloo Paratha",1,"Food",["Potato","Stuffed","Butter","Punjab","Breakfast"]],
["Cutting Chai",1,"Food",["Half","Tea","Glass","Mumbai","Tapri"]],
["Chowmein",1,"Food",["Noodles","Chinese","Street","Fried","Wok"]],
["Rajma Chawal",1,"Food",["Beans","Rice","Sunday","Punjab","Curry"]],
["Ola",1,"Brands",["Cab","App","Ride","Book","Uber"]],
["Selfie",1,"Daily Life",["Photo","Phone","Camera","Pose","Front"]],
["WhatsApp",1,"Tech",["Chat","Message","Green","Forward","Group"]],
["Aadhaar",1,"Daily Life",["Card","Number","ID","Twelve","UIDAI"]],
["Paytm",1,"Brands",["Wallet","Recharge","UPI","Karo","App"]],
["Namaste",1,"Hinglish",["Hello","Greeting","Hands","Fold","Bow"]],
["Kulfi",1,"Food",["Ice Cream","Stick","Frozen","Malai","Pista"]],
["Bhelpuri",1,"Food",["Puffed","Rice","Chaat","Beach","Mumbai"]],
["Chhota Bheem",1,"TV",["Cartoon","Laddoo","Dholakpur","Kids","Strong"]],
["Amul",1,"Brands",["Butter","Girl","Milk","Utterly","Gujarat"]],
["Parle-G",1,"Brands",["Biscuit","Girl","Tea","Glucose","Cheap"]],
["Butter Chicken",1,"Food",["Punjab","Gravy","Tomato","Naan","Cream"]],
["Idli",1,"Food",["Steamed","Rice","South","Round","Sambar"]],
["Thali",1,"Food",["Plate","Meal","Unlimited","Variety","Katori"]],
["Achaar",1,"Food",["Pickle","Mango","Oil","Spicy","Jar"]],
["Papad",1,"Food",["Crispy","Roast","Lijjat","Thin","Fry"]],
["Kurkure",1,"Brands",["Snack","Crunchy","Masala","Munch","Chips"]],
["Zomato",1,"Brands",["Food","Delivery","App","Order","Swiggy"]],
// ---------- MEDIUM ----------
["Golden Temple",2,"Places",["Amritsar","Sikh","Punjab","Langar","Harmandir"]],
["Kumbh Mela",2,"Festivals",["Ganga","Bath","Sadhu","Prayagraj","Crowd"]],
["Rakhi",2,"Festivals",["Thread","Sister","Brother","Wrist","Raksha Bandhan"]],
["Karwa Chauth",2,"Festivals",["Fast","Moon","Wife","Sieve","Husband"]],
["Onam",2,"Festivals",["Kerala","Sadya","Boat","Pookalam","Mahabali"]],
["Pongal",2,"Festivals",["Tamil","Harvest","Rice","Sugarcane","Sun"]],
["Durga Puja",2,"Festivals",["Bengal","Pandal","Kolkata","Goddess","Dhunuchi"]],
["Navratri",2,"Festivals",["Garba","Nine","Dandiya","Gujarat","Nights"]],
["Eid",2,"Festivals",["Sewai","Moon","Ramzan","Biryani","Namaz"]],
["Baraat",2,"Culture",["Groom","Horse","Band","Dance","Wedding"]],
["Sangeet",2,"Culture",["Wedding","Dance","Song","Night","Family"]],
["Bidaai",2,"Culture",["Bride","Cry","Leave","Wedding","Farewell"]],
["Dabbawala",2,"Daily Life",["Mumbai","Lunch","Tiffin","Deliver","Bicycle"]],
["Local Train",2,"Daily Life",["Mumbai","Crowd","Rush","Compartment","Ladies"]],
["Chandni Chowk",2,"Places",["Delhi","Market","Old","Paratha","Crowd"]],
["Marine Drive",2,"Places",["Mumbai","Sea","Queen","Necklace","Promenade"]],
["Gateway of India",2,"Places",["Mumbai","Monument","Sea","Taj Hotel","Arch"]],
["Red Fort",2,"Places",["Delhi","Independence","Flag","Mughal","Lal Qila"]],
["India Gate",2,"Places",["Delhi","War","Memorial","Amar Jawan","Ice Cream"]],
["Qutub Minar",2,"Places",["Delhi","Tower","Tall","Minaret","Iron Pillar"]],
["Hawa Mahal",2,"Places",["Jaipur","Pink","Windows","Palace","Wind"]],
["Charminar",2,"Places",["Hyderabad","Four","Minarets","Old City","Bangles"]],
["Howrah Bridge",2,"Places",["Kolkata","River","Hooghly","Steel","Cantilever"]],
["Konark",2,"Places",["Odisha","Sun","Temple","Wheel","Chariot"]],
["Kerala Backwaters",2,"Places",["Houseboat","Alleppey","Coconut","Lake","Canal"]],
["Ladakh",2,"Places",["Mountain","Bike","Pangong","Buddhist","Cold"]],
["Kashmir",2,"Places",["Valley","Shikara","Dal Lake","Paradise","Snow"]],
["Rishikesh",2,"Places",["Ganga","Rafting","Yoga","Beatles","Laxman Jhula"]],
["Varanasi",2,"Places",["Ghat","Ganga","Aarti","Banaras","Temple"]],
["Jaipur",2,"Places",["Pink","City","Rajasthan","Palace","Fort"]],
["Udaipur",2,"Places",["Lake","Palace","Rajasthan","City","White"]],
["Bengaluru",2,"Places",["IT","Traffic","Garden","Silicon","Bangalore"]],
["Hyderabad",2,"Places",["Biryani","Charminar","Nizam","Pearls","Cyberabad"]],
["Kolkata",2,"Places",["Bengal","Tram","Howrah","Rosogolla","Calcutta"]],
["Chennai",2,"Places",["Madras","Marina","Tamil","Filter Coffee","Beach"]],
["Ahmedabad",2,"Places",["Gujarat","Sabarmati","Dhokla","Gandhi","Kite"]],
["Bajaj",2,"Brands",["Scooter","Hamara","Chetak","Pulsar","Auto"]],
["Tata",2,"Brands",["Ratan","Salt","Steel","Nano","Group"]],
["Reliance",2,"Brands",["Jio","Ambani","Mukesh","Sim","Antilia"]],
["Flipkart",2,"Brands",["Shopping","Online","Big Billion","Amazon","Sale"]],
["Royal Enfield",2,"Brands",["Bullet","Bike","Thump","Classic","Ladakh"]],
["Maruti",2,"Brands",["Car","Suzuki","Alto","Swift","800"]],
["Kingfisher",2,"Brands",["Beer","Mallya","Airline","Bird","Calendar"]],
["Thums Up",2,"Brands",["Cola","Taste","Thunder","Drink","Salman"]],
["Fevicol",2,"Brands",["Glue","Stick","Ad","Bond","Jod"]],
["Lifebuoy",2,"Brands",["Soap","Health","Red","Hai Jahan","Bath"]],
["Chyawanprash",2,"Brands",["Immunity","Amla","Jam","Winter","Dabur"]],
["Rasgulla",2,"Food",["Bengal","Sweet","Spongy","Syrup","White"]],
["Mysore Pak",2,"Food",["Sweet","Karnataka","Ghee","Besan","Yellow"]],
["Chole Bhature",2,"Food",["Chickpea","Fried","Puri","Delhi","Punjab"]],
["Dhokla",2,"Food",["Gujarat","Steamed","Besan","Yellow","Spongy"]],
["Pav Bhaji",2,"Food",["Mumbai","Bread","Butter","Mash","Vegetable"]],
["Filter Coffee",2,"Food",["South","Tamil","Steel","Tumbler","Decoction"]],
["Litti Chokha",2,"Food",["Bihar","Sattu","Baingan","Roasted","Wheat"]],
["Rogan Josh",2,"Food",["Kashmir","Mutton","Red","Curry","Lamb"]],
["Sarson ka Saag",2,"Food",["Punjab","Mustard","Makki","Roti","Winter"]],
["Ilish",2,"Food",["Fish","Bengal","Bones","Mustard","Hilsa"]],
["Kaju Katli",2,"Food",["Cashew","Sweet","Diamond","Silver","Diwali"]],
["Bhindi",2,"Food",["Okra","Lady Finger","Vegetable","Green","Sabzi"]],
["3 Idiots",2,"Movies",["Aamir","Rancho","All is well","College","Engineering"]],
["Sholay",2,"Movies",["Gabbar","Jai","Veeru","Basanti","Kitne Aadmi"]],
["DDLJ",2,"Movies",["Raj","Simran","Train","Switzerland","Maratha Mandir"]],
["Dangal",2,"Movies",["Wrestling","Aamir","Geeta","Babita","Haryana"]],
["Baahubali",2,"Movies",["Katappa","Prabhas","Mahishmati","Why","Rajamouli"]],
["RRR",2,"Movies",["Naatu","Ram Charan","NTR","Oscar","Rajamouli"]],
["Lagaan",2,"Movies",["Cricket","Aamir","British","Tax","Bhuvan"]],
["Amitabh Bachchan",2,"Movies",["Big B","Angry","KBC","Actor","Jaya"]],
["Rajinikanth",2,"Movies",["Thalaiva","Superstar","Tamil","Style","Robot"]],
["Salman Khan",2,"Movies",["Bhai","Bigg Boss","Shirtless","Dabangg","Bhaijaan"]],
["Aamir Khan",2,"Movies",["Perfectionist","3 Idiots","Dangal","Mr","Actor"]],
["Deepika Padukone",2,"Movies",["Ranveer","Actress","Padmaavat","Dimples","Om Shanti Om"]],
["Priyanka Chopra",2,"Movies",["Nick Jonas","Miss World","Desi Girl","Hollywood","Actress"]],
["A.R. Rahman",2,"Music",["Music","Oscar","Jai Ho","Composer","Roja"]],
["Lata Mangeshkar",2,"Music",["Singer","Nightingale","Voice","Legend","Melody"]],
["Kishore Kumar",2,"Music",["Singer","Yodel","Voice","Old","Songs"]],
["KBC",2,"TV",["Quiz","Amitabh","Crorepati","Lock","Lifeline"]],
["Bigg Boss",2,"TV",["Reality","House","Salman","Nomination","Weekend"]],
["Taarak Mehta",2,"TV",["Jethalal","Gokuldham","Comedy","Serial","Babita"]],
["CID",2,"TV",["Daya","Darwaza","ACP","Pradyuman","Crime"]],
["Ramayan",2,"Mythology",["Valmiki","Sita","Ravan","Lanka","Epic"]],
["Mahabharat",2,"Mythology",["Kurukshetra","Pandav","Kaurav","Krishna","Epic"]],
["Krishna",2,"Mythology",["Flute","Blue","Butter","Radha","Gokul"]],
["Shiva",2,"Mythology",["Trishul","Third Eye","Kailash","Nandi","Destroyer"]],
["Ravan",2,"Mythology",["Ten","Heads","Lanka","Dussehra","Villain"]],
["Arjun",2,"Mythology",["Archer","Pandav","Krishna","Bow","Draupadi"]],
["Karna",2,"Mythology",["Kavach","Kundal","Sun","Generous","Mahabharat"]],
["Gandhi",2,"History",["Bapu","Charkha","Non-violence","Salt","Father"]],
["Nehru",2,"History",["First","Prime Minister","Jacket","Rose","Chacha"]],
["Bhagat Singh",2,"History",["Freedom","Hanged","Revolution","Inquilab","Lahore"]],
["APJ Abdul Kalam",2,"History",["Missile","President","Scientist","Wings of Fire","Rameswaram"]],
["Rabindranath Tagore",2,"History",["Nobel","Jana Gana Mana","Poet","Bengal","Gitanjali"]],
["Chandrayaan",2,"Tech",["Moon","ISRO","Rocket","Lander","Vikram"]],
["ISRO",2,"Tech",["Space","Rocket","Satellite","Bengaluru","Mars"]],
["UPI",2,"Tech",["Payment","QR","Scan","PhonePe","GPay"]],
["Hockey",2,"Sports",["Stick","National","Dhyan Chand","Olympic","Goal"]],
["Neeraj Chopra",2,"Sports",["Javelin","Gold","Olympic","Throw","Tokyo"]],
["PV Sindhu",2,"Sports",["Badminton","Shuttle","Olympic","Medal","Hyderabad"]],
["Mary Kom",2,"Sports",["Boxing","Manipur","Punch","Olympic","Magnificent"]],
["Kapil Dev",2,"Cricket",["1983","World Cup","Haryana","Hurricane","All-rounder"]],
["Rohit Sharma",2,"Cricket",["Hitman","Mumbai","Captain","Opener","264"]],
["Tiffin",2,"Daily Life",["Lunch","Box","Steel","Office","Dabba"]],
["Chappal",2,"Daily Life",["Slipper","Footwear","Kolhapuri","Rubber","Sandal"]],
["Nazar",2,"Hinglish",["Evil Eye","Lemon","Chilli","Kala Tika","Battu"]],
["Bandh",2,"Hinglish",["Strike","Shutdown","Protest","Close","Hartal"]],
["Log Kya Kahenge",2,"Hinglish",["People","Say","Society","Think","Judge"]],
["Arranged Marriage",2,"Culture",["Parents","Rishta","Match","Bio-data","Family"]],
["Bargaining",2,"Daily Life",["Price","Haggle","Discount","Market","Bhaiya"]],
["Dupatta",2,"Culture",["Scarf","Salwar","Drape","Cloth","Kameez"]],
["Lungi",2,"Culture",["Cloth","Wrap","South","Waist","Dhoti"]],
["Tiranga",2,"Culture",["Flag","Saffron","White","Green","Tricolour"]],
["Antakshari",2,"Games",["Song","Game","Letter","Last","Sing"]],
["Kho Kho",2,"Games",["Chase","Game","Sit","Tag","Pole"]],
["Haldi",2,"Food",["Turmeric","Yellow","Wedding","Spice","Doodh"]],
["Ghee",2,"Food",["Butter","Clarified","Cow","Desi","Cooking"]],
["Gur",2,"Food",["Jaggery","Sugar","Brown","Sugarcane","Sweet"]],
["Tulsi",2,"Nature",["Basil","Plant","Holy","Courtyard","Leaves"]],
["Neem",2,"Nature",["Tree","Bitter","Datun","Leaves","Medicine"]],
["Darjeeling",2,"Places",["Tea","Hills","Toy Train","Kanchenjunga","Bengal"]],
["Andaman",2,"Places",["Islands","Cellular Jail","Beach","Scuba","Bay of Bengal"]],
["Kanyakumari",2,"Places",["Tip","South","Sunrise","Three Seas","Vivekananda"]],
["Tirupati",2,"Places",["Balaji","Laddoo","Temple","Andhra","Hair"]],
["Vaishno Devi",2,"Places",["Katra","Trek","Jammu","Cave","Mata"]],
["Kedarnath",2,"Places",["Shiva","Uttarakhand","Trek","Flood","Himalaya"]],
["Demonetisation",2,"History",["Notes","500","1000","Ban","2016"]],
["Sensex",2,"Daily Life",["Stock","Market","Bombay","Index","Dalal Street"]],
// ---------- HARD ----------
["Sanskrit",3,"Culture",["Language","Ancient","Vedas","Shloka","Devanagari"]],
["Ashoka Chakra",3,"Culture",["Flag","Wheel","Blue","24","Spokes"]],
["Panchayat",3,"Daily Life",["Village","Sarpanch","Council","Local","Gram"]],
["Chai Pe Charcha",3,"Hinglish",["Modi","Tea","Talk","Discussion","Election"]],
["Aunty",3,"Hinglish",["Neighbour","Gossip","Beta","Society","Uncle"]],
["Kal",3,"Hinglish",["Tomorrow","Yesterday","Day","Time","Aaj"]],
["Rishta",3,"Hinglish",["Proposal","Marriage","Aunty","Match","Arranged"]],
["Sasta",3,"Hinglish",["Cheap","Price","Mehenga","Discount","Deal"]],
["Jhoola",3,"Daily Life",["Swing","Rope","Tree","Park","Push"]],
["Baniyan",3,"Daily Life",["Vest","Undershirt","Cotton","White","Sleeveless"]],
["Ghunghat",3,"Culture",["Veil","Bride","Face","Cover","Pallu"]],
["Anarkali",3,"Culture",["Suit","Dress","Flared","Mughal","Salim"]],
["Kohinoor",3,"History",["Diamond","Queen","Britain","Crown","Stolen"]],
["Vande Mataram",3,"History",["Song","National","Bankim","Freedom","Motherland"]],
["Jana Gana Mana",3,"Culture",["Anthem","Tagore","National","52 Seconds","Stand"]],
["Chai Sutta",3,"Hinglish",["Tea","Cigarette","Tapri","Break","Friends"]],
["Nukkad",3,"Hinglish",["Corner","Street","Natak","Gully","Chai"]],
["Adda",3,"Hinglish",["Hangout","Gossip","Bengali","Friends","Chat"]],
["Sarkar",3,"Hinglish",["Government","Modi","Power","State","Ruling"]],
["Babu",3,"Hinglish",["Clerk","Government","Office","File","Bureaucrat"]],
["Chaiwala",3,"Daily Life",["Tea","Seller","Modi","Tapri","Kettle"]],
["Ambassador Car",3,"History",["Hindustan","White","Government","Old","Kolkata"]],
["Doordarshan",3,"TV",["Channel","Government","Old","Logo","DD"]],
["Shaktimaan",3,"TV",["Superhero","Mukesh Khanna","Spin","Gangadhar","Serial"]],
["Mile Sur Mera Tumhara",3,"TV",["Song","Unity","Doordarshan","Anthem","Old"]],
["Rasna",3,"Brands",["Drink","Powder","I Love You","Orange","Summer"]],
["Nirma",3,"Brands",["Detergent","Washing","Powder","Girl","Jingle"]],
["Bournvita",3,"Brands",["Chocolate","Milk","Powder","Cadbury","Kids"]],
["Boroline",3,"Brands",["Cream","Green","Tube","Antiseptic","Bengal"]],
["Old Monk",3,"Brands",["Rum","Dark","Bottle","Cheap","Winter"]],
["Gilli Danda",3,"Games",["Stick","Game","Village","Hit","Wood"]],
["Lagori",3,"Games",["Stones","Ball","Game","Seven","Pithu"]],
["Kanche",3,"Games",["Marbles","Glass","Game","Flick","Kids"]],
["Chhath Puja",3,"Festivals",["Bihar","Sun","River","Fast","Soop"]],
["Bihu",3,"Festivals",["Assam","Dance","Harvest","Festival","Bohag"]],
["Hornbill Festival",3,"Festivals",["Nagaland","Tribe","Dance","December","Kohima"]],
["Pushkar Mela",3,"Festivals",["Camel","Rajasthan","Fair","Desert","Lake"]],
["Jallikattu",3,"Festivals",["Bull","Tamil","Pongal","Tame","Ban"]],
["Kathakali",3,"Culture",["Kerala","Dance","Face","Green","Makeup"]],
["Bharatanatyam",3,"Culture",["Dance","Classical","Tamil","Mudra","Ghungroo"]],
["Sitar",3,"Music",["Instrument","Strings","Ravi Shankar","Classical","Music"]],
["Tabla",3,"Music",["Drum","Zakir Hussain","Beat","Pair","Classical"]],
["Ghungroo",3,"Music",["Anklet","Bells","Dance","Sound","Feet"]],
["Madhubani",3,"Culture",["Painting","Bihar","Art","Folk","Mithila"]],
["Warli",3,"Culture",["Painting","Tribal","Maharashtra","Stick Figures","White"]],
["Pashmina",3,"Culture",["Shawl","Kashmir","Wool","Soft","Expensive"]],
["Banarasi",3,"Culture",["Sari","Silk","Varanasi","Wedding","Zari"]],
["Kanjeevaram",3,"Culture",["Sari","Silk","Tamil","Wedding","Gold"]],
["Ayurveda",3,"Culture",["Medicine","Herbs","Ancient","Vaidya","Dosha"]],
["Sattu",3,"Food",["Bihar","Flour","Gram","Drink","Litti"]],
["Kokum",3,"Food",["Konkan","Fruit","Sherbet","Sour","Purple"]],
["Chikki",3,"Food",["Peanut","Jaggery","Lonavala","Brittle","Sweet"]],
["Bhut Jolokia",3,"Food",["Chilli","Assam","Hot","Ghost","Spicy"]],
["Nagpur Orange",3,"Food",["Santra","Fruit","Maharashtra","City","Citrus"]],
["Sundarbans",3,"Places",["Mangrove","Tiger","Bengal","Delta","Forest"]],
["Rann of Kutch",3,"Places",["White","Desert","Salt","Gujarat","Festival"]],
["Hampi",3,"Places",["Ruins","Karnataka","Vijayanagara","Boulders","UNESCO"]],
["Khajuraho",3,"Places",["Temple","Sculptures","Madhya Pradesh","Carvings","Chandela"]],
["Ajanta Ellora",3,"Places",["Caves","Maharashtra","Buddhist","Kailasa","Paintings"]],
["Meenakshi Temple",3,"Places",["Madurai","Gopuram","Colourful","Tamil","Goddess"]],
["Amarnath",3,"Places",["Cave","Ice","Lingam","Yatra","Kashmir"]],
["Bodh Gaya",3,"Places",["Buddha","Enlightenment","Tree","Bihar","Bodhi"]],
["Sabarmati Ashram",3,"History",["Gandhi","Ahmedabad","River","Charkha","Dandi"]],
["Jallianwala Bagh",3,"History",["Amritsar","Massacre","Dyer","1919","Bullet"]],
["Dandi March",3,"History",["Salt","Gandhi","Walk","1930","Tax"]],
["Chipko Movement",3,"History",["Trees","Hug","Uttarakhand","Forest","Women"]],
["Green Revolution",3,"History",["Wheat","Farming","Swaminathan","Punjab","Yield"]],
["Operation Flood",3,"History",["Milk","Amul","Kurien","White Revolution","Dairy"]],
["GST",3,"Daily Life",["Tax","Goods","Services","One Nation","Bill"]],
["Lok Sabha",3,"Daily Life",["Parliament","MP","Lower House","Election","543"]],
["Rajya Sabha",3,"Daily Life",["Upper House","Parliament","Elders","MP","States"]],
["Supreme Court",3,"Daily Life",["Judge","Delhi","Verdict","Chief Justice","Law"]],
["RBI",3,"Daily Life",["Bank","Governor","Reserve","Repo","Currency"]],
["Mangalyaan",3,"Tech",["Mars","ISRO","Orbit","Cheap","Mission"]],
["Dhyan Chand",3,"Sports",["Hockey","Wizard","Olympic","Gold","Stick"]],
["Milkha Singh",3,"Sports",["Flying Sikh","Runner","Race","Bhaag","Athlete"]],
["Sunil Chhetri",3,"Sports",["Football","Captain","Goal","Bengaluru","Striker"]],
["Viswanathan Anand",3,"Sports",["Chess","Grandmaster","Champion","Chennai","King"]],
["Anil Kumble",3,"Cricket",["Spinner","Ten Wickets","Jumbo","Bengaluru","Leg Spin"]],
["Rahul Dravid",3,"Cricket",["Wall","Coach","Defence","Bengaluru","Mr Dependable"]],
["Jasprit Bumrah",3,"Cricket",["Yorker","Fast","Bowler","Action","Mumbai Indians"]],
["Chak De India",3,"Movies",["Hockey","Shah Rukh","Coach","Girls","Sattar Minute"]],
["Gully Boy",3,"Movies",["Rap","Ranveer","Dharavi","Apna Time","Murad"]],
["Andhadhun",3,"Movies",["Blind","Piano","Ayushmann","Tabu","Rabbit"]],
["Drishyam",3,"Movies",["Ajay Devgn","Mohanlal","Police Station","Cover Up","2nd October"]],
["Zindagi Na Milegi Dobara",3,"Movies",["Spain","Road Trip","Hrithik","Tomatina","Friends"]],
["Kantara",3,"Movies",["Kannada","Bhoota Kola","Rishab Shetty","Forest","Deity"]],
["Anupam Kher",3,"Movies",["Actor","Bald","Kashmir Files","DDLJ Dad","Veteran"]],
["Nana Patekar",3,"Movies",["Actor","Loud","Welcome","Uday","Marathi"]],
["Chai Biscuit",3,"Food",["Tea","Dip","Parle","Marie","Evening"]],
["Bhutta",3,"Food",["Corn","Roasted","Lemon","Monsoon","Cob"]],
["Kanji",3,"Food",["Carrot","Fermented","Drink","Black","Holi"]],
];
